program: ./dtu_mlops_age_prediction/train_model_sweep.py
method: random
name: sweep

metric:
  goal: maximize
  name: val_acc

parameters:
  batch_size: 
    values: [16,32,64,128]

  lr:
    min: 0.00001
    max: 0.001

  epochs:
    values: [5, 10, 15]
