wandb_version: 1

batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.0007913862331664184
program:
  desc: null
  value: ./dtu_mlops_age_prediction/train_model_sweep.py
method:
  desc: null
  value: random
name:
  desc: null
  value: sweep
metric:
  desc: null
  value:
    goal: maximize
    name: val_acc
parameters:
  desc: null
  value:
    batch_size:
      values:
      - 16
      - 32
      - 64
      - 128
    lr:
      min: 1.0e-05
      max: 0.001
    epochs:
      values:
      - 5
      - 10
      - 15
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705498370.597152
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      - 105
      2:
      - 1
      - 41
      - 49
      - 55
      - 63
      - 105
      3:
      - 16
      - 23
      - 37
      4: 3.11.7
      5: 0.16.2
      8:
      - 3
      - 5
      13: windows-amd64
