name: "Code Check"

on: 
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  code-check:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install ruff and mypy
      run: |
        python -m pip install --upgrade pip
        pip install ruff mypy

    - name: Run ruff check and format
      run: |
        ruff check
        ruff format

    - name: Run mypy
      run: |
        mypy .